pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: '4d7cdeb2-d39c-4d75-af23-ea1a6e59c603', 
                url: 'https://github.com/NishitRai/Jenkins-project.git',
                branch: 'test'
           }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh('echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin')
                }
            }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t nish536/todo-app:${BUILD_NUMBER} python-jenkins-argocd-k8s/.
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Dockerhub Repo'
                    docker push nish536/todo-app:${BUILD_NUMBER}
		    docker logout
                    '''
                }
            }
        }
/*        
        stage('Checkout K8S manifest SCM'){
            steps {
                git credentialsId: '4d7cdeb2-d39c-4d75-af23-ea1a6e59c603', 
                url: 'https://github.com/NishitRai/cicd-demo-manifests-repo.git',
                branch: 'main'
            }
        }
*/        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    withCredentials([usernamePassword(credentialsId: '4d7cdeb2-d39c-4d75-af23-ea1a6e59c603', passwordVariable: 'GIT_PASS', usernameVariable: 'GIT_USER')]) {
                        sh '''
			cd python-jenkins-argocd-k8s/deploy/
                        cat deploy.yaml
			sed -i "s/todo-app:.*$/todo-app:${BUILD_NUMBER}/g" deploy.yaml                        
                        cat deploy.yaml
			git config --global user.email "Jenkins@example.com"
  			git config --global user.name "Jenkins"
                        git add deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git remote set-url origin https://$GIT_USER:$GIT_PASS@github.com/Jenkins-project.git
			git remote -v
			git push origin test
#                        git push https://github.com/iam-veeramalla/cicd-demo-manifests-repo.git HEAD:test
                        '''                        
                    }
                }
            }
        }
    }
}
